import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useNavigate } from 'react-router-dom';
import { Task } from '../../../models/task.model';
import { TaskService } from '../api';
import { Status, Priority } from '../types';
import './CreateTaskForm.css';

// Validation schema using zod
const taskFormSchema = z.object({
  title: z.string().min(1, "Назва є обов'язковим полем"),
  description: z.string().min(1, "Опис є обов'язковим полем"), // Backend вимагає опис (мінімум 1 символ)
  status: z.enum(['todo', 'in-progress', 'review', 'done']),
  priority: z.enum(['low', 'normal', 'high']),
  deadline: z
    .string()
    .optional()
    .refine(
      date => {
        if (!date) return true; // Optional field
        const selectedDate = new Date(date);
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        return selectedDate >= today;
      },
      {
        message: 'Дедлайн не може бути в минулому',
      }
    ),
});

type TaskFormData = z.infer<typeof taskFormSchema>;

export function CreateTaskForm() {
  const navigate = useNavigate();
  const taskService = new TaskService();

  const {
    register,
    handleSubmit,
    formState: { errors, isValid },
    reset,
  } = useForm<TaskFormData>({
    resolver: zodResolver(taskFormSchema),
    mode: 'onChange',
    defaultValues: {
      status: 'todo',
      priority: 'normal',
    },
  });

  const onSubmit = async (data: TaskFormData) => {
    try {
      // Create Task instance with new Date() for createdAt
      const task = new Task(
        '', // id will be generated by the server
        data.title,
        data.description, // Backend вимагає опис
        new Date(), // createdAt
        data.status as Status,
        data.priority as Priority,
        data.deadline || undefined
      );

      await taskService.createTask(task);
      reset();

      // Navigate to tasks list after successful creation
      navigate('/tasks');
    } catch (error) {
      alert(
        `Помилка створення завдання: ${error instanceof Error ? error.message : 'Невідома помилка'}`
      );
      console.error('Помилка створення завдання:', error);
    }
  };

  return (
    <div className="form-section">
      <h2>Створити нове завдання</h2>
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className="form-group">
          <label htmlFor="title">Назва:</label>
          <input
            type="text"
            id="title"
            {...register('title')}
            className={errors.title ? 'error' : ''}
          />
          {errors.title && <span className="error-message">{errors.title.message}</span>}
        </div>

        <div className="form-group">
          <label htmlFor="description">Опис:</label>
          <textarea
            id="description"
            rows={4}
            {...register('description')}
            className={errors.description ? 'error' : ''}
          />
          {errors.description && (
            <span className="error-message">{errors.description.message}</span>
          )}
        </div>

        <div className="form-group">
          <label htmlFor="status">Статус:</label>
          <select id="status" {...register('status')} className={errors.status ? 'error' : ''}>
            <option value="todo">To Do</option>
            <option value="in-progress">In Progress</option>
            <option value="review">Review</option>
            <option value="done">Done</option>
          </select>
          {errors.status && <span className="error-message">{errors.status.message}</span>}
        </div>

        <div className="form-group">
          <label htmlFor="priority">Пріоритет:</label>
          <select
            id="priority"
            {...register('priority')}
            className={errors.priority ? 'error' : ''}
          >
            <option value="low">Низький</option>
            <option value="normal">Нормальний</option>
            <option value="high">Високий</option>
          </select>
          {errors.priority && <span className="error-message">{errors.priority.message}</span>}
        </div>

        <div className="form-group">
          <label htmlFor="deadline">Дедлайн:</label>
          <input
            type="date"
            id="deadline"
            {...register('deadline')}
            className={errors.deadline ? 'error' : ''}
          />
          {errors.deadline && <span className="error-message">{errors.deadline.message}</span>}
        </div>

        <button type="submit" disabled={!isValid}>
          Створити завдання
        </button>
      </form>
    </div>
  );
}
